ip2region_path: ip2region.xdb
my_email: shuyuzheng19@gmail.com
blog_search_index: zsy-blogs
origin:
  urls: http://192.168.0.109:8080
  methods: GET,POST,DELETE,PUT
server:
  addr: 0.0.0.0
  port: 8888
ip: &ip 192.168.25.147
blog_page_cache: true #是否开启博客分页缓存
blog_page_cache_expire: 2 #需要启用博客分页缓存 单位小时
gpt:
  token: 
  cookie: 
  api: 
db:
  username: username
  password: password
  host: *ip
  path: shuyu_blog
  port: 5432
  max_content: 10
logger:
  disable_error: true
  copy_path: path
  regex: ^/api/v1/(tags|category)/.*,^/api/v1/blog/(hots|range|latest|recommend|similar)
  excludes:
  log_path: controller_info.log
redis:
  host: *ip
  port: 6379
  password: password
  db: 0
  max_size: 10
  min_idle: 2
smtp:
  username: username
  password: password
  host: smtp.163.com
  addr: smtp.163.com:25
meilisearch:
  host: http://blog.shuyuz.com:7700
  api_key: api_key
token:
  secret: asdasd8a4s8d14as!~~
  expire: 7 #单位天
upload:
  avatar: avatar
  image: image
  files: files
  max_image_size: 5
  max_file_size: 300
  prefix: 
  uri: 
  path: 
